### ISSUE TITLE
Reconsider the specification of "JAVA VOICE"(ジャバ音をどうするか)

### ISSUE THREAD

**Issue by tobynet** [arigato-java/javabound#1]
Need to reconsider the functional specification, "Java Voice" or "Sit".
Those are conflicted.
# Expected
1. First, the player presses `interact key` **[E]**  on **Red Button** or **Ancient Button**.
   (Blue).
2. Then, the player **can hear "JAVA VOICE"**.

(ジャバボタン近くで、"E"を押すと、ジャバ音が鳴る想定があった。)
# Actual
1. The player presses `interact key` **[E]** on **Red Button** or **Ancient Button**.
   (Blue).
2. The character of player **sit on it**.

It's a conflict of the specification!!!!!

(実際には、ジャバボタン近くで"E"を押すと、ボタンの上に座る。座ると、連続で Eを押せない。仕様上の矛盾がある。)

**Comment by tomari** [comment]
Starbound側の仕様の確認がまだですが、攻撃でジャバ音が出るようにするとかはできるのではないでしょうか。

**Comment by tobynet** [comment]
殴って音がなる物体が作れるか、要調査ですね。

---

もしくは、以下のように別のオブジェクトにしてしまう案もあります。
グラフィックやアイコンを区別可能にするという問題を解決できれば、僕は分けてしまいたいです。

> ベンチとは違う他のジャバボタンを用意してスイッチいれるとジャバが出てくるようにしましょう

via https://twitter.com/esehara/status/776580594390163456

(ゲーム中の座れるものは、ソファーや椅子、ベンチっぽい形状をしています。 押せるものはボタンやスイッチっぽいです。アイコンは 「無」と「料」で、機能が違うくらいの方がジャバ感あると思います)

---

また、あんまりな案としては、左右（か上下）にぶった切って、「左は座れ」、「右は鳴らせる」という案もあります。

**Comment by tobynet** [comment]
**「ジャバ感ありつつも、ゲーム内の調和を乱さない」** という所に落とし込みたく思います。

「調和」に関して： 「他のオブジェクトと操作法がまったく違う」事を避けたい意味

**Comment by tobynet** [comment]
「ジャバ音が鳴るボタン」と「座れるボタン」を 分けました。

3227b2002dc77eef92137acab07fa3efa5cd6570
