### ISSUE TITLE
Adjust length of some description

### ISSUE THREAD

**Issue by tobynet** [arigato-java/javabound#10]
Ops, some messages overflow..
- [ ] A : [javabo-block_ja](https://github.com/arigato-java/javabound/blob/6918943/src/objects/javabound/javabo-block_ja.object#L8) ジャバブロック(置物)
- [ ] B : [javabo_ja](https://github.com/arigato-java/javabound/blob/6918943/src/objects/javabound/javabo_ja.object#L8) 赤いジャバボタン
- [ ] C : [javabo-blue_ja](https://github.com/arigato-java/javabound/blob/6918943/src/objects/javabound/javabo-blue_ja.object#L8) 青いジャバボタン

![A - in the crafting](https://i.gyazo.com/b03b63fb6f3248895fb18b8d549385a4.png) ![A - in the inventory ](https://i.gyazo.com/7ddeae545ab69a95a1b387a018bda8d0.png)

![B](https://i.gyazo.com/95a201525a51703b5c5c45f410557540.png) ![B - in the inventory](https://i.gyazo.com/f95d5f1d6b1e27c323738177f64693df.png)

![C - in the crafting](https://i.gyazo.com/11ad2003b470b7ebb72a1f523f9a8255.png) ![C - in the inventory](https://i.gyazo.com/5c9fbe6ea52fc8747e05a239e0052189.png)
## OK な examples:
- OK : [Sign of Java 2](https://github.com/arigato-java/javabound/blob/6918943/src/objects/javabound/javacopy-java-you_ja.object#L8)

> The first line of the sign that accompanies a Javabutton. (lang:ja)

![OK - Sign of Java 2](https://gyazo.com/d043254a86532d359734e6143a883e56.png)

Default asset
- [Inventor's Table](http://starbounder.org/Inventor%27s_Table)

> The inventor's table is used to produce various crafting stations

![OK- Inventors Table](https://i.gyazo.com/6bac491654884ca164eddd741d171be9.png)

**Comment by tomari** [comment]
検証ありがとうございます。急ぎ対応いたします。

**Comment by tomari** [comment]
ド　https://github.com/arigato-java/javabound/pull/11

**Comment by tobynet** [comment]
GJ. Thanks!!

![](https://i.gyazo.com/4e41706f9444d9bf947e8184645cc7db.png)

![](https://i.gyazo.com/4cbc9365315706a12f4756963f210760.png)

![](https://i.gyazo.com/e00c26d74293e8af1282594d6d2b0baf.png)

今どきのDPIでとるスクショはデカい、、、
