### ISSUE TITLE
Update usage in README considering Creafting Station

### ISSUE THREAD

**Issue by tobynet** [arigato-java/javabound#14]
Fix mismatching of instructions.
- [x] Fix readme 

📝  New screenshots can wait.
## Expected
1. Run game.
2. Hit C key to **craft `Inventor's Table`**.
3. **Place it**.
4. **Hit E key to craft `Java Factory` on table**.
5. **Place it** .
6. **Hit E key to craft Java artifact on `Java goods`**.
7. Place it. 
8. Have Javaaaaa
## Actual(past)

Run game -> Hit C key to craft Java artifact -> Place it -> Have Java

**Comment by tomari** [comment]
本件、確認しておりますが、こちらのチームの人員の問題で少々お時間頂きます。

**Comment by tomari** [comment]
ダウンロードエンジニア3人日分割り当てられました。3人日とは、その人が3日間徹夜した時の累積の作業量です。

**Comment by tobynet** [comment]
ありがとうございます。

**Comment by tobynet** [comment]
Screenshots も update して push いたしました!! 
Thank you for your contribution!
