### ISSUE TITLE
Check translation ( description,  shortDescription)

### ISSUE THREAD

**Issue by tobynet** [arigato-java/javabound#5]
In [src/objects/javabound/*.object](https://github.com/arigato-java/javabound/tree/master/src/objects/javabound)
- `description` : For in the detail window. ([e.x. 1](https://github.com/arigato-java/javabound/blob/a956ea6/src/objects/javabound/javabo-block_ja.object#L8))
- `shortDescription` :  For in the item list. ([e.x. 2](https://github.com/arigato-java/javabound/blob/a956ea6/src/objects/javabound/javabo-block_ja.object#L9))

Check List:
- [x] &nbsp; [javabo-block_ja](https://github.com/arigato-java/javabound/blob/6f5daae/src/objects/javabound/javabo-block_ja.object#L8-L9) 赤いジャバボタン
- [x] &nbsp; [javabo-blue_ja](https://github.com/arigato-java/javabound/blob/6f5daae/src/objects/javabound/javabo-blue_ja.object#L8-L9) 青いジャバボタン
- [x] &nbsp; [javabo-block_ja](https://github.com/arigato-java/javabound/blob/6f5daae/src/objects/javabound/javabo-block_ja.object#L8-L9) ジャバブロック(置物)
- [x] &nbsp; [javacopy-java-you_ja](https://github.com/arigato-java/javabound/blob/6f5daae/src/objects/javabound/javacopy-java-you_ja.object#L8-L9) 「あなたとジャバ,」 
- [x] &nbsp; [javacopy-downloa-today_ja](https://github.com/arigato-java/javabound/blob/6f5daae/src/objects/javabound/javacopy-downloa-today_ja.object#L8-L9): 「今すぐダウンロー」
- [x] &nbsp; [javacopy-do_ja](https://github.com/arigato-java/javabound/blob/6f5daae/src/objects/javabound/javacopy-do_ja.object#L8-L9) 「ド」

Figure.1 In the crafting window:
[![https://gyazo.com/9dcefd9f26d11381240439c7b44f3492](https://i.gyazo.com/9dcefd9f26d11381240439c7b44f3492.png)](https://gyazo.com/9dcefd9f26d11381240439c7b44f3492)

Figure.2 In the inventory:
[![https://gyazo.com/e67a339d514f71697aa240202a080ca1](https://i.gyazo.com/e67a339d514f71697aa240202a080ca1.png)](https://gyazo.com/e67a339d514f71697aa240202a080ca1)

**ジャバ感と世界の調和をバランスに**

**Comment by tomari** [comment]
あなたとジャバ https://github.com/arigato-java/javabound/pull/8
