### ISSUE TITLE
Check translation (README.md , Description in the Steam Workshop )

### ISSUE THREAD

**Issue by tobynet** [arigato-java/javabound#6]
- [x] &nbsp; [README.md](https://github.com/arigato-java/javabound/blob/master/README.md)
- [ ] &nbsp;  [Steam Workshop](http://steamcommunity.com/sharedfiles/filedetails/?id=763323158)
  
  [![https://gyazo.com/75bcec926936767953569d6e8fee607f](https://i.gyazo.com/75bcec926936767953569d6e8fee607f.png)](https://gyazo.com/75bcec926936767953569d6e8fee607f)

(どちらも大体同じ文面)

**Comment by tomari** [comment]
ｺﾞｶｸﾆﾝ! ｺﾞｶｸﾆﾝ! https://github.com/arigato-java/javabound/pull/12

**Comment by tobynet** [comment]
Steam の方は、READMEをﾓﾄﾆ チョウセーいたします！！
