### ISSUE TITLE
Check translation (description for races )

### ISSUE THREAD

**Issue by tobynet** [arigato-java/javabound#7]
apexDescription 等の `*Description` は、[種族別](http://starbounder.org/Races) のコメントです。  ([e.x. 3](https://github.com/arigato-java/javabound/blob/a956ea6/src/objects/javabound/javabo-block_ja.object#L12-L18))

表示される場面:
- **[N]** によるサーチの際に表示される。 (序盤クエスト終了後に使えるかも？)
- NPCが近くに来て、勝手に感想を話すときにも

種族事の性格で口調が変わるので、文面が難しい。 このIssueはあと回しでよい。

---

例えば、`apexDescription` が対象とするapexは、「ビッグブラザーに支配された知能あるおサルさんのイメージ」だったり、 hylotl は侍、東アジアっぽいイメージだったりします。

Figure.1 : glitchDescription at [javabo_ja](https://github.com/arigato-java/javabound/blob/a956ea6/src/objects/javabound/javabo_ja.object#L15)

[![https://gyazo.com/277b7962d9c6a772ee3c869d4ec51b52](https://i.gyazo.com/277b7962d9c6a772ee3c869d4ec51b52.png)](https://gyazo.com/277b7962d9c6a772ee3c869d4ec51b52)

Figure.1 glitchDescription at [javacopy_java-you_ja](https://github.com/arigato-java/javabound/blob/a956ea6/src/objects/javabound/javacopy-java-you_ja.object#L15)

[![https://gyazo.com/1b879046c06935111582fe7ab8e80b79](https://i.gyazo.com/1b879046c06935111582fe7ab8e80b79.png)](https://gyazo.com/1b879046c06935111582fe7ab8e80b79)

見た目はペンギンですが、中身は glitch だったりします。
## note:

現状、hylotl はジャバクラスタと仮定して、ジャバジャバ言わせています。

**Comment by tomari** [comment]
Merge request https://github.com/arigato-java/javabound/pull/22

求職者が、どうしてもジャバをダウンロードしたくない、という主張をする場合があります。そういう場合、私たちはあえて「オラクル」を提案します。オラクルでは、ジャバをアップロードすることさえあれ、ダウンロードすることはないのです。逆転の発想ですが、こういった特殊なケースを解決するにはこのような柔軟な対応力が必要になります。

**Comment by tobynet** [comment]
ジャバリクありがとうございます。早速マージさせていただきました。
名description感謝いたします。オラクルのご加護があらんことを。
