### ISSUE TITLE
The naming and the appearance of `Crafting Station` for Java goods

### ISSUE THREAD

**Issue by tobynet** [arigato-java/javabound#9]
**It** generates "Crimson Javabutton" and blue one, some "Sign of Java", etc...
- [x] What should we call **it**? (the naming)
- [x] What does **it** look like? (the appearance)
# Ref.

Starbound default:

![](http://starbounder.org/mediawiki/images/a/ae/Crafting_Stations.png)

Furnace: 炉 。 鉱石をインゴットに変換。
[![https://gyazo.com/eb7531748b9f91e61bdb879d21ed8586](https://i.gyazo.com/eb7531748b9f91e61bdb879d21ed8586.png)](https://gyazo.com/eb7531748b9f91e61bdb879d21ed8586)

Workbench: 家具やブロック、置物をつくる
[![https://gyazo.com/355cb7ce06e742449857cc902987973f](https://i.gyazo.com/355cb7ce06e742449857cc902987973f.png)](https://gyazo.com/355cb7ce06e742449857cc902987973f)

Replicator: 武器防具をつくるもの
[![https://gyazo.com/a9f2e1b4c69f908f88a3cf1288ac19e2](https://i.gyazo.com/a9f2e1b4c69f908f88a3cf1288ac19e2.png)](https://gyazo.com/a9f2e1b4c69f908f88a3cf1288ac19e2)

via http://starbounder.org/Crafting_Station

**Comment by tomari** [comment]
オラクル本社をモチーフにしたリソースを作るしかないのではないでしょうか。

**Comment by tobynet** [comment]
Ideas 

## 0: `Java Station`(without Logo)

Ref. https://en.wikipedia.org/wiki/JavaStation 

![](http://www.98server.org/hyper98/images/JavaStation_1a.JPG)

## 1:  Fat `JavaButton`

(recursive)

[![https://gyazo.com/da79c6ee6728f48a72dace30f4ee3778](https://i.gyazo.com/da79c6ee6728f48a72dace30f4ee3778.png)](https://gyazo.com/da79c6ee6728f48a72dace30f4ee3778)

## 2: `Mother Computer`

It looks like a supercomputer. (Crimson painted)

## 3: `Website Builder`

(This is a top secret for Java Developer.)

Ref.
![](http://img.futureworld.jp/?category=sn&img_name=hpb19_value_ac_m1.jpg) 

## 5: `Coffee Maker` : (Need a symbolize, like a combini's one )

Ref. 

![](http://blogs.timeout.jp/en/wp-content/uploads/2013/08/7-Eleven-Coffee-crop-528x685.jpg)

Ref. [サン・マイクロシステムズの廃墟ビルに残されたサーバールーム - GIGAZINE](http://gigazine.net/news/20071221_abandone_server/)

**Comment by tobynet** [comment]
入れ違いでした。

O社モチーフならばこういうのもいいかな。

![](http://images.gofreedownload.net/misc-database-28508.jpg)

via [その他のデータベース-アイコン-無料のアイコン 無料でダウンロード](http://ja.gofreedownload.net/free-icon/icons/misc-database-109423/)

![db-blue.png 440×500](http://publicdomainvectors.org/photos/db-blue.png)

via [青いデータベース アイコン ベクトル画像 | パブリックドメインのベクトル](http://publicdomainvectors.org/ja/%E7%84%A1%E6%96%99%E3%82%AF%E3%83%AA%E3%83%83%E3%83%97%E3%82%A2%E3%83%BC%E3%83%88/%E9%9D%92%E3%81%84%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9-%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B3-%E3%83%99%E3%82%AF%E3%83%88%E3%83%AB%E7%94%BB%E5%83%8F/17373.html)

![](https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Applications-database.svg/240px-Applications-database.svg.png)

via [File:Applications-database.svg - Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Applications-database.svg)

**Comment by tomari** [comment]
その後ずっと本件について考えていたのですが、現実世界ではジャバボタンこそがすべてのジャバの"Crafting Station"であるのではないでしょうか。ジャバーバウンドが現実世界のメタファーとして作られているとするなら、我々はなにか大きな勘違いをしていたかもしれません。

**Comment by tobynet** [comment]
素晴らしい着眼点です。 

 私としては、生産装置としてのジャバボを用意する事は、「DB型のジャバ生産工場」を用意するのと同じくらい賛成です。 その際の実装は、通常のジャバボとはデータを分ける形になると思われます。(理由は後述)

---

以下、余談。

当初、ジャバーバウンドは、「現実世界でのジャバ活動を、仮想世界で行うとどうなるか」「ジャバ文学の世界観を表せられないか」という2つの個人的な思いからfoundしております。 
（そのため、真っ先にリリースしたものが、壁画的に背景に貼り付けられる Java Sign と Button なのであります） 

さて、ジャバボタンからジャバが生まれるとする考え方は、現実の（ジャバの）メタファーに違いありません。
個人的には、リカーシヴであり、ジャバ文脈として遜色ない案と思いました。

技術的な問題点があるとすると、Starbound の制約上、一つのオブジェクトに（ここではジャバボタン）に、多くの機能を持たせられない事です。 

例えば、Issue #1 であったように、 「押すと鳴る鳴るジャバ音」と「座る」、またここでいう「ジャバを生み出す」は、同じオブジェクトに同時に実装しようとすると、 Starbound の操作感を損なうことになります。

※ これは Starbound の仕様。 異なる行動の操作を分けず、 単独 のInteraction （[E]キーによるもの） から、「買い物する」「押す」「座る/寝る」 など、文脈毎に異なる動作をプレイヤーに提供しているため。 まさに、ジャバで知られたポリモーフィズムであり、興味深い点。

**Comment by tobynet** [comment]
長くなり、要旨がはっきりしないので、再投稿します。  私としては、下記 1 の方向性を押します。
1. ゲームとして、Starbound のMODとして自然な形であるのは、 上に画像で上げた「DB型ジャバ生産工場」や「コーヒーメーカー」であるに違いありません。  Starbound の crafting システムともマッチします。 
2. 「ジャバボタンからジャバが生まれる」事は、ジャバクラスタにとってはジャバをダウンロードすることのように自然です。 同時に、哲学的ですらあります。 しかし、 Starbound プレイヤーから見た場合、標準システムから離れたものであり、混乱の元ではないかと考えます。
   （僕もつい採用したく暴れる右手を抑えこみ、こらえています。）

**Comment by tomari** [comment]
仰るとおり、世界観の統一、大切だと思います。上記議論に異論ありません。

ところで、エクリプスやネットビーンズも悪くないな、と先ほど思いつきました。これらもジャバを生成するものとして自然なものかと思います。

**Comment by tobynet** [comment]
いくつか作ってみました。  ([v1.1-alpha.4](https://github.com/arigato-java/javabound/releases/tag/v1.1-alpha.4) で試せます。)

データベースっぽいやつ (`Java Factory` )

![](https://i.gyazo.com/4cee7837da71add16f0f03a7fcd65c94.gif)

サーバーっぽいやつ その1  (`Java Server(2U)`, 現在 Storage として機能 )

![](https://i.gyazo.com/03ed6554069250f21b9c386d932a40f9.gif) 

サーバーっぽいやつその2 (`Java Server(8U)`, 現在 Storage として機能  )

![](https://i.gyazo.com/4fa25f4564e061dcf3da125964aa05fb.gif)

※ サーバーは画像を作る際の部品として使う予定でもあります。
例えば、「2Uの画像をベースに、上にエクリプス風の画像を載せる等」

**Comment by tobynet** [comment]
v1.1 向けに `Java Factory` という名前で、DB風画像のもので一旦リリースすることにしました。
placeholder として考えてもらっても構いません。
